name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: ./pkg
      - run: npm test
        working-directory: ./pkg
      - run: npm run build
        working-directory: ./pkg

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
        working-directory: ./pkg
      - run: npm run build
        working-directory: ./pkg
      - run: npm publish --access public
        working-directory: ./pkg
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
